In [1]:
import requests
import pandas as pd
from getpass import getpass
import json
import os
from bs4 import BeautifulSoup
import re
import matplotlib.pyplot as plt

In [24]:
rent = pd.read_csv('/Users/juniorlinhares/Documents/projects/Project-Data-Pipeline/data/Barcelona_rent_price.csv')

In [25]:
rent

,Year,Trimester,District,Neighbourhood,Average _rent (euro/month),Average _rent per surface (euro/m2)
0,2014,1,Ciutat Vella,el Raval,589.55,10.76
1,2014,1,Ciutat Vella,Gothic Quarter,712.79,10.58
2,2014,1,Ciutat Vella,la Barceloneta,540.71,14.40
3,2014,1,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",673.44,11.01
4,2014,1,Eixample,Fort Pienc,736.09,10.42
...,...,...,...,...,...,...
2306,2022,2,Sant Marti,Diagonal Mar i el Front Maritim del Poblenou,1238.70,17.50
2307,2022,2,Sant Marti,el Besos i el Maresme,779.20,12.20
2308,2022,2,Sant Marti,Provencals del Poblenou,1032.90,14.60
2309,2022,2,Sant Marti,Sant Marti de Provencals,843.00,11.90
2310,2022,2,Sant Marti,la Verneda i la Pau,757.00,11.40

In [26]:
average_rent_per_year = rent.groupby('Year')['Average _rent (euro/month)'].mean().round(2)
average_rent_per_year_list = average_rent_per_year.tolist()
average_rent_per_year_list

[661.64, 695.24, 750.96, 829.38, 874.05, 923.32, 915.92, 871.59, 922.55]

In [29]:
rent['Year'] = rent['Year'].astype(int)
segmented_data = rent.groupby('District')
mean_rental_prices = segmented_data['Average _rent (euro/month)'].mean()
sorted_rental_prices = mean_rental_prices.sort_values(ascending=False)

In [30]:
rent_sorted = rent.sort_values(by='Average _rent (euro/month)', ascending=False)
rent_unique = rent_sorted.drop_duplicates(subset='Neighbourhood', keep='first')
top_3_neighbourhoods = rent_unique.head(3)
top_3_neighbourhoods

,Year,Trimester,District,Neighbourhood,Average _rent (euro/month),Average _rent per surface (euro/m2)
430,2015,3,Les Corts,Pedralbes,2034.00,17.00
2266,2022,2,Sarria-Sant Gervasi,les Tres Torres,1767.00,16.90
226,2014,4,Sarria-Sant Gervasi,"Vallvidrera, el Tibidabo i les Planes",1754.44,15.88